function result = createMask_synap(RGB,filename)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 04-Nov-2019
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.095;
channel1Max = 0.348;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.000;
channel2Max = 0.144;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.000;
channel3Max = 0.595;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;
BW_out = bwareafilt(BW, 1000);
prop_table = regionprops(BW_out, {'Area','FilledArea','BoundingBox', 'Eccentricity', 'EquivDiameter', 'EulerNumber', 'MajorAxisLength', 'MinorAxisLength', 'Orientation', 'Perimeter'});
area = zeros(length(prop_table),1);
filled_area = zeros(length(prop_table),1);
for i=1:length(prop_table)
    area(i)=prop_table(i,1).Area;
    filled_area(i) = prop_table(i,1).FilledArea;
end
v=roipoly(RGB);
per_area=sum(area)/sum(v(:));
num_pixels = sum(area);
save([char(filename) '.mat']);
result = [per_area,num_pixels]
end
