function ForwardDynamics = ForwardDynamics_gen(in1,in2)
%FORWARDDYNAMICS_GEN
%    FORWARDDYNAMICS = FORWARDDYNAMICS_GEN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    12-Feb-2020 17:14:31

dq1 = in1(5,:);
dq2 = in1(6,:);
dq3 = in1(7,:);
dq4 = in1(8,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
t2 = cos(q4);
t3 = sin(q2);
t4 = sin(q4);
t5 = dq2+dq4;
t6 = q2+q4;
t7 = dq2.^2;
t11 = -dq2;
t12 = -dq4;
t13 = -q2;
t14 = -q4;
t8 = t2.^2;
t10 = sin(t6);
t15 = t2.*1.0e+1;
t16 = t2.*5.8e+1;
t17 = t2./2.0;
t18 = t2.*1.32e+2;
t19 = t2+7.0./2.0;
t24 = (dq2.*dq4.*t4)./2.0;
t26 = (t4.*t7)./2.0;
t30 = (dq4.*t4.*t5)./2.0;
t31 = t3.*1.4715e+1;
t9 = t8.^2;
t20 = t8.*2.0;
t21 = t8.*8.0;
t23 = t8.*2.0e+1;
t25 = t8.*3.6e+2;
t28 = -t26;
t29 = t17+5.0./4.0;
t32 = t10.*(9.81e+2./2.0e+2);
t22 = t9.*1.6e+1;
t27 = -t25;
t33 = t15+t20+2.5e+1;
t34 = t16+t21+9.5e+1;
t35 = t18+t23+2.21e+2;
t38 = dq3+q3+t12+t14+t28+t32;
t39 = dq1+q1+t11+t13+t24+t30+t31+t32;
t36 = t22+t27+2.025e+3;
t37 = 1.0./t36;
t40 = t29.*t34.*t37.*1.6e+1;
t41 = -t40;
ForwardDynamics = [dq1;dq2;dq3;dq4;dq1.*-2.0+dq2.*2.0-q1.*2.0+q2.*2.0+tau1.*2.0;-t39.*(t40-t19.*t33.*t37.*3.2e+1)-t38.*(t19.*t34.*t37.*1.6e+1-t29.*t35.*t37.*1.6e+1);dq3.*-2.0+dq4.*2.0-q3.*2.0+q4.*2.0+tau2.*2.0;-t39.*(t34.*t37.*2.0e+1-t29.*t33.*t37.*3.2e+1)-t38.*(t40-t35.*t37.*2.0e+1)];
